### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by maban** [maban/styleguides#310]
Over the Christmas break, I'm going to dedicate some time to enhancing styleguides.io. Is there anything you'd like me to work on in particular?

**Comment by bradfrost** [comment]
Wonderful, @maban! 
I think a feature that would be helpful for a lot of people would be the ability to filter tools (http://styleguides.io/tools.html) by technology type. Lots of people ask me "Do you know any good ruby (or similar)-based style guide tools?" So that could be helpful!

I'll have a think about other stuff. Thanks for dedicating the time to this! Wish I could do the same :p

**Comment by maban** [comment]
Ahh yes, good idea @bradfrost! We have tags for examples, so could use the same functionality there.

**Comment by brendanfalkowski** [comment]
I'd like to rework the filters, because they work ok but it's hard to tell which are on/off without resetting. They could definitely be abstracted to work for other content types.

Other ideas:

1. In the card grid, the floats/clears are a bit messy (especially with filters on). We could update the card grid with flexbox and get nice uniform-height boxes that always wrap properly.

2. The home page is a monster (881 list items). It's hard to get a broad sense of what's in the site because you have to scroll so far to see each section heading. We could reduce this to one card per section with a short paragraph + compact list of starred content + link to full section list. I think that'd be more inviting to explore (at the expense of one giant index to use "CMD + F" on).

**Comment by maban** [comment]
@brendanfalkowski I'd love to apply some more styling to the filters to make the on/off state clearer, and make them more clickable. I can try and abstract them myself, unless you're eager to work on it. 😀

1. Yes! I'd like to maybe use Grid as well, since it's coming to browsers soon.
2. Ugh, totally. That'll be my priority. I had no idea we'd get so much content! Good problem to have, though.

**Comment by maban** [comment]
I've made some quick and dirty updates, in particular to the filters (now using tags, at least for the moment, because filters make more sense for when you have lots and lots of tags). It's using jQuery which I'd like to convert into vanilla JS.

I've also restricted the number of items on the homepage to only show the recommended resources, although I like @brendanfalkowski's suggestion of enhancing it further. I hope to get round to that.

Still going, moving onto the grid styles so they work better when the tags are selected.

**Comment by maban** [comment]
### Progress…

![screen shot 2016-12-29 at 17 53 56](https://cloud.githubusercontent.com/assets/237149/21550212/f19d749c-cdef-11e6-88cb-55bb4c32963f.png)
![screen shot 2016-12-29 at 17 54 19](https://cloud.githubusercontent.com/assets/237149/21550211/f19c9ff4-cdef-11e6-8230-f14757e89ecd.png)
![screen shot 2016-12-29 at 17 54 37](https://cloud.githubusercontent.com/assets/237149/21550213/f1a034e8-cdef-11e6-9463-527a14354dcf.png)

**Comment by maban** [comment]
Just pushed some more changes to prod. Making more improvements.

**Comment by maban** [comment]
Ok, all enhancements requested are live. I need to clean up the code a bit, there's a lot of messy inline scripts and stuff.
