### ISSUE TITLE
Consolidate GitHub styleguide examples

### ISSUE THREAD

**Issue by michaelthorne** [maban/styleguides#41]
Just a question, I see that there are two examples for GitHub: http://styleguides.io/examples.html

They're both all part of their "styleguide", based on the URL: https://github.com/styleguide which includes CSS, JavaScript & Ruby coding guidelines, as well as a short section on HTML & Templates.

So should we not just have one example, pointing to: https://github.com/styleguide

The reason I ask, is that I was going to add their Mobile Web styleguide to the examples: https://github.com/styleguide/mobile but it's really just a section/part of the whole thing.

**Comment by brendanfalkowski** [comment]
I added the GitHub styleguide (I think), but chose not to reference each section individually. Same goes for the "mobile" section since it's part of the company's overarching styleguide.

I think we should limit one entry per project/company, except in a case like MailChimp where they have separate sites for patterns, voice, etc. The tagging should handle make it easy enough to find "code" guides without calling out specific languages.

**Comment by michaelthorne** [comment]
Agreed on the limit of one entry per project/company! :+1:

Especially if that website has (clear) navigation to browse other related sections.

**Comment by bradfrost** [comment]
Yep I think keeping it simple is a good idea. So long as the style guides are navigable and things are tagged appropriately, we should be good. Of course there are exceptions (MailChimp as noted above), but for the most part consolidating the URLs is a good idea.

I'm going to close this out for now.
