### ISSUE TITLE
Hover transforms on resource modules causing lag + flickering

### ISSUE THREAD

**Issue by joelparr** [maban/styleguides#46]
Not sure if it's lack of GPU-enabled rendering or what, but if I hover over any of the resource module boxes (each li.resource) there is a distinct lag before the scale transform kicks in and the content of every  <li> flickers, making even scrolling through hand exploring the resources seem super janky on my machine. 

Safari Version 8.0 (10600.1.25) on Yosemite 10.10 on a late 2013 13" Retina MBP.

PS. Thanks again or the great resource.

**Comment by brendanfalkowski** [comment]
Hi Joel, unfortunately that's just Safari being a lame duck. The flickering happens when elements are promoted or demoted to GPU rendered layers as when transitions are applied. Most browsers get this right (including Mobile Safari) but WebKit for Safari Mac has always been wonky with rendering.

Looks like the GH Pages template was only coded for WebKit (d'oh) so you won't see the transitions in Firefox or IE.

**Comment by joelparr** [comment]
Yeah, understood. If you want to take the slightly hacky route, making each li.resource a block element with -webkit-transform set to translateZ(0) (since we don't have to worry about FF or IE!) seems to pull safari nicely into line for me.

**Comment by brendanfalkowski** [comment]
Just added the other vendor-prefixes but it looks like Safari is still janky.

**Comment by maban** [comment]
I added a fix this morning: https://github.com/maban/styleguides/commit/cd8ad6d75f38e2f2c3e72e90514b8da9c4addeda – same thing?

**Comment by joelparr** [comment]
Yep, that's the one.

**Comment by brendanfalkowski** [comment]
Ah, right. translate3d on the element not the state. Good catch Anna!
