### ISSUE TITLE
New tool resource RSCSS

### ISSUE THREAD

**Issue by montogeek** [maban/styleguides#91]
RSCSS

Reasonable Stardard\* for CSS Stylesheet Structure.
https://github.com/rstacruz/rscss

**Comment by bradfrost** [comment]
Hey @montogeek,
Thanks for sharing RSCSS. It looks like this is a CSS methodology like BEM, OOCSS, or SMACSS, is that correct? If that's what it is, I don't know if this site is the best place for it. The site focuses on tools for maintaining style guides and pattern libraries rather than specific CSS methodologies.

If I'm misunderstanding this and this has to do with style guides and pattern libraries, let me know and I'll take another look!

**Comment by montogeek** [comment]
Yes, is more like a methodology. What if this site add a section for methodologies?

**Comment by bradfrost** [comment]
I'd love to see a resource site that rounds up CSS methodologies! However, I don't think it's this site. Again, the focus here is on creating and maintaining pattern libraries/style guides rather than individual methodologies.

But yeah, I'd fully support that project!
